/* This file is part of the Spring engine (GPL v2 or later), see LICENSE.html */

/*
 * The C entry points the native (C) AI Interface resolves via dlsym. They are
 * thin forwarders to the Go-exported functions (see aiexport.go), because Go
 * cannot export a symbol named `init`.
 */

#include "ExternalAI/Interface/aidefines.h"

struct SSkirmishAICallback;

/* Declarations generated by cgo from the //export directives in aiexport.go. */
#include "_cgo_export.h"

EXPORT(int) init(int skirmishAIId, const struct SSkirmishAICallback* callback) {
	return goInit(skirmishAIId, (void*)callback);
}

EXPORT(int) release(int skirmishAIId) {
	return goRelease(skirmishAIId);
}

EXPORT(int) handleEvent(int skirmishAIId, int topic, const void* data) {
	return goHandleEvent(skirmishAIId, topic, (void*)data);
}
